### ISSUE TITLE
Why is a test dataset required

### ISSUE THREAD

**Issue by robvanderg** [danielvarab/uniparse#10]
Dear Daniel, 

I am tuning a parser, why am I forced to get scores on test directly? (or even dev actually?)

**Comment by danielvarab** [comment]
Hi Rob! This made me chuckle considering how much we've talked about splits the past couple of years. There is no good reason for this whatsoever and it's about time this repo gets some love. I see you've addressed this, as well as issue #9 in PR #11.

I'll check the branch out this weekend, and probably add the same changes to the remaining scripts and merge it to master! 🙌

**Comment by danielvarab** [comment]
#11 is now merged. Will address dev/test requirements in dynet implementations separately.
